### ISSUE TITLE
TypeError: Cannot read property 'attribute_id' of null

### ISSUE THREAD

**Issue by ghost** [vuestorefront/vue-storefront-1#378]
## Current behavior
error: Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'attribute_id' of null
      at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/produc
t.js:256:47)
      at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37
      at Array.map (<anonymous>)
      at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js
:260:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: 
{
  message: "Cannot read property 'attribute_id' of null",
  stack: "TypeError: Cannot read property 'attribute_id' of null\n" +
    '    at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/pro
duct.js:256:47)\n' +
    '    at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37\n' 

* 

```
'    at Array.map (<anonymous>)\n' +
'    at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product
```

.js:260:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}

## Expected behavior
It should import products

## Steps to reproduce the issue
Run yarn mage2vs import it happens sometime and sometime it works

## Version of Vue Storefront

* [ ] Vue Storefront -- ## [1.12.3] 

## Can you handle fixing this bug by yourself?
* [x] NO

## Environment details

* Browser: NA
* OS: Linux
* Node: 12.18.3
* Code Version: [1.12.3]

**Comment by AlexGene06** [comment]
By default, Vue Storefront API docker files and config are based on Elastic 5.6. We plan to change the default Elastic version to 7 with the 1.11 stable release. As for now, the Elastic 7 support is marked as experimental.

In order to index data to Elastic 7 please make sure you set the proper apiVersion in the config.js:

  elasticsearch: {
    apiVersion: process.env.ELASTICSEARCH_API_VERSION || '7.1'
  },
or just use the env variable:

export ELASTICSEARCH_API_VERSION=7.1
